Update main123.yml

diff --git a/.github/workflows/main123.yml b/.github/workflows/main123.yml
--- a/.github/workflows/main123.yml
+++ b/.github/workflows/main123.yml
@@ -28,11 +28,19 @@ jobs:
       - name: Build Project (Maven)
         run: mvn clean package -DskipTests=true  # If using Maven
 
-      - name: Run Suite JAR from Target Directory
+      
+
+      - name: Execute Tests
         run: |
-             cd target
-              echo "🚀 Running Suite JAR..."
-              java -jar rajeshthevampire-1.0.0-jar-with-dependencies.jar
+          set -e  # Stop script on errors
+          cd target
+          echo "✅ Listing files before execution..."
+          ls -lah
+          echo "✅ Running Java Test..."
+          java -jar rajeshthevampire-1.0.0-jar-with-dependencies.jar || echo "❌ Test execution failed, but continuing."
+          echo "✅ Listing files before execution..."
+          ls -lah
+ 
 
 
       # Debugging Step: List files in target directory
