Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,7 +42,7 @@ jobs:
           echo "✅ Listing files before execution..."
           ls -lah
           echo "✅ Running Java Test..."
-          java -jar rajeshthevampire-1.0.0-jar-with-dependencies.jar || echo "❌ Test execution failed, but continuing."
+          java -jar rajeshthevampire-1.0.0-jar-with-dependencies.jar --debug || echo "❌ Test execution failed, but continuing."
 
       - name: Find Report File
         run: |
